working on stderr/stdout handling for windows pharo

diff --git a/bin/createPharoTodeClient b/bin/createPharoTodeClient
--- a/bin/createPharoTodeClient
+++ b/bin/createPharoTodeClient
@@ -39,6 +39,16 @@ EXAMPLES
 
 HELP
 }
+win_error_exit() {
+echo "Error on or near line $1"
+cat ${directoryPath}/stderr
+}
+win_run_pharo(){
+trap 'win_error_exit ${LINENO}' ERR
+$directoryPath/Pharo.exe --headless $*
+trap - ERR
+cat $directoryPath/stdout
+}
 
 set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
@@ -94,7 +104,7 @@ PLATFORM="`uname -sm | tr ' ' '-'`"
 
 case "$PLATFORM" in
   MINGW32_NT*)
-    pharoCmd="$directoryPath/Pharo.exe --headless"
+    pharoCmd=win_run_pharo
     todeLoadPath=$GS_SHARED_TODE/sys/default/pharo/windows/todeLoad.st
     if [ -e $GS_SHARED_TODE/sys/local/pharo/windows/todeLoad.st ] ; then
       todeLoadPath=$GS_SHARED_TODE/sys/local/pharo/windows/todeLoad.st
